### ISSUE TITLE
Write SXSW Design Research Proposal

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/design#98]

**Comment by heyitsolivia** [comment]
Leaving these words here since it may be useful to reference:

**Intended audience**

> Designers, technologists and program creators that work in the space of civic tech

**Session Idea (700 characters, including spaces)**

> Building smart civic services that address the needs of real people has become more critical than ever. The chaotic launch of Healthcare.gov brought wide public attention to the dangers of poorly created tools. Human centered design is no longer optional when it comes to civic tech.
> Understanding and developing compassion for our audience allows us to serve them better. Design research is a deliberate process of asking the right people the right questions to ensure that we are creating solutions with empathy for real users.
> We will teach techniques and tips for crafting a successful design research process, sharing best practices and addressing the unique challenges in the space of civic tech.

**Distilled Session Description (200 characters)**

> Building smart civic services for real people is more critical than ever. We will teach techniques for crafting a successful design research process, addressing the unique challenges of civic tech.

**List the 3 questions that your session will answer regarding the topic proposed. Please do not put a number in front of your questions. (150 characters for each question)**

> What unique challenges exist in designing effective tools for civic tech?
> How can we craft questions that will yield genuine responses in the user research process? 
> What human factors are important to consider when conducting interviews?
